spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: LibraryProject
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    redisson:
      file: classpath:redisson.yml


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

